<?php

class api_code
{
    public static $errCode = [
        'en' => [
            '0'    => 'success',
            '1'    => 'failure',
            '1000' => 'request param empty',
            '1001' => 'missed required param',
            '1002' => 'access key valid failed',
            '1003' => 'user token auth failed',
            '1004' => 'username not valid',
            '1005' => 'user password not valid',
            '1006' => 'user login failed',
            '1007' => 'page value not valid required int type',
            '1008' => 'length value not valid required int type',
            '1009' => 'teacherId value not valid required int type',
            '1010' => 'planId value not valid required int type',
            '1011' => 'have not begin to class,get voice stream info failed',
            '1012' => 'mobile phone number format error',
            '1013' => 'mobile phone number can not be empty',
            '1014' => 'mobile phone verification code can not be empty',
            '1015' => 'password can not be empty',
            '1016' => 'repeat password can not be empty',
            '1017' => 'passwords can not be chinese or special characters',
            '1018' => 'passwords can not be less than six characters more than twenty characters',
            '1019' => 'two password input is not consistent',
            '1020' => 'user Id value not valid required int type',
            '1021' => 'no landing',
            '1022' => 'parameter type is not valid',
            '1023' => 'parameter type is not name',
            '1024' => 'Is not a legitimate user',
            '1025' => "You can't collect yourself",
            '1026' => 'Error third party landing type',
            '1027' => 'Did not choose to upload files',
            '1028' => 'Generate file failed',
            '1029' => 'Upload file failed',
            '1030' => 'tag id tag name can not be empty at the same time',
            '1031' => 'No third party landing information was detected',
            '1032' => 'Cell phone number bound failed',
            '1033' => 'To update the article information does not exist',
            '1034' => 'Tag update, after the success of the new failure',
            '1035' => 'Tag update, delete failed',
            '1036' => 'Failed to publish articles when Synchronous mapping table',
            '1037' => 'Not binding',
            '1038' => 'Wrong password, please enter again',
            '1039' => 'login failed',
            '1040' => 'Please enter the account number',
            '1041' => 'Please enter a password',
            '1042' => 'Illegal land',
            '1043' => 'The number of words is beyond the limits',
            '2000' => 'get teacher course list failed',
            '2001' => 'teacher no permission teaching',
            '2002' => 'living has not start',
            '2003' => 'living has over',
            '2004' => 'At the same time teacher can only teach one lession',
            '2005' => 'play failed',
            '2006' => 'course mesosphere get data failed',
            '2007' => 'plan mesosphere get data failed',
            '2008' => 'teacher mesosphere get data failed',
            '2009' => 'user mobile phone number has been registered',
            '2010' => 'verification code transmission failure',
            '2011' => 'mobile phone verification code does not match',
            '2012' => 'registration failure',
            '2013' => 'update password failure',
            '2014' => 'the mobile phone number is not yet registered',
            '2015' => 'failed to send a registered successful SMS',
            '3000' => 'system error',
            '3001' => 'system salt value not set',
            '3002' => 'get data failed',
        ],
        'zh' => [
            '0'    => '操作成功',
            '1'    => '操作失败',
            '1000' => '请求参数为空',
            '1001' => '缺少必传参数',
            '1002' => '请求key验证失败',
            '1003' => '用户token 验证失败',
            '1004' => '不是有效的用户名',
            '1005' => '不是有效的密码',
            '1006' => '用户登陆失败',
            '1007' => '分页page参数类型错误，需要整数',
            '1008' => '分页length参数类型错误，需要整数',
            '1009' => '老师ID不是有效的整数',
            '1010' => 'planId不是有效的整数',
            '1011' => '获取语音流失败，还未开始上课',
            '1012' => '手机号格式错误',
            '1013' => '手机号码不能为空',
            '1014' => '手机验证码不能为空',
            '1015' => '密码不能为空',
            '1016' => '重复的密码不能为空',
            '1017' => '密码不能为特殊的字符和中文',
            '1018' => '密码必须在6-20个字符之间',
            '1019' => '两次输入的密码不一致',
            '1020' => '用户id不是有效的整数',
            '1021' => '不是当前登陆用户',
            '1022' => '参数类型不合法',
            '1023' => '用户名不能为空',
            '1024' => '不是合法的登陆用户',
            '1025' => '自己不能收藏自己',
            '1026' => '错误的第三方登陆类型',
            '1027' => '没有选择上传文件',
            '1028' => '生成文件失败',
            '1029' => '上传文件失败',
            '1030' => '标签id和名称不能同时为空',
            '1031' => '没有检测到第三方登陆信息',
            '1032' => '手机号绑定失败',
            '1033' => '要更新的文章信息不存在',
            '1034' => 'tag 更新,删除成功之后新增失败',
            '1035' => 'tag 更新,删除失败',
            '1036' => '不服文章同步数据失败',
            '1037' => '尚未绑定',
            '1038' => '密码错误，请重新输入',
            '1039' => '登陆失败',
            '1040' => '请输入账号',
            '1041' => '请输入密码',
            '1042' => '非法登陆',
            '1043' => '字数超出了限制',
            '2000' => '获取教师课程列表失败',
            '2001' => '老师没有权限上课',
            '2002' => '直播课还未开始',
            '2003' => '直播已经结束',
            '2004' => '同一时间老师只能直播一节课',
            '2005' => 'pc端上课失败',
            '2006' => '课程中间层获取数据失败',
            '2007' => '排课中间层获取数据失败',
            '2008' => '老师中间层获取数据失败',
            '2009' => '用户手机号已经注册',
            '2010' => '获取手机验证码失败',
            '2011' => '用户手机号和验证码不匹配',
            '2012' => '用户注册失败',
            '2013' => '更新用户密码失败',
            '2014' => '用户手机号还未注册',
            '2015' => '用户注册成功之后，发送短信失败',
            '3000' => '系统内部错误',
            '3001' => '系统salt未设置',
            '3002' => '获取数据失败'
        ]
    ];








}
